--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Maio-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AUTOR" 
   (	"ID_AUTOR" NUMBER, 
	"NOME" VARCHAR2(50 BYTE), 
	"NACIONALIDADE" VARCHAR2(50 BYTE), 
	"ANO_NASCIMENTO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LIVRO" 
   (	"ID_LIVRO" NUMBER, 
	"TITULO_LIVRO" VARCHAR2(100 BYTE), 
	"ISBN_LIVRO" VARCHAR2(10 BYTE), 
	"EDICAO_LIVRO" NUMBER, 
	"DESCRICAO_LIVRO" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRO_AUTOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LIVRO_AUTOR" 
   (	"ID_LIVRO" NUMBER, 
	"ID_AUTOR" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_AUTOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_ID_AUTOR" ON "SYSTEM"."AUTOR" ("ID_AUTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ID_LIVRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_ID_LIVRO" ON "SYSTEM"."LIVRO" ("ID_LIVRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LIVRO_AUTOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_LIVRO_AUTOR" ON "SYSTEM"."LIVRO_AUTOR" ("ID_LIVRO", "ID_AUTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger AUTOR_INCREMENT_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."AUTOR_INCREMENT_ID" 
  BEFORE INSERT ON autor
  FOR EACH ROW
BEGIN
  SELECT autor_sequence.nextval
  INTO :new.id_autor
  FROM dual;
END;
/
ALTER TRIGGER "SYSTEM"."AUTOR_INCREMENT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LIVRO_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."LIVRO_TRIGGER" 
BEFORE INSERT ON LIVRO
FOR EACH ROW
BEGIN
SELECT LIVRO_SEQUENCE.NEXTVAL INTO :NEW.ID_LIVRO FROM DUAL;
END;
/
ALTER TRIGGER "SYSTEM"."LIVRO_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AUTOR" ADD CONSTRAINT "PK_ID_AUTOR" PRIMARY KEY ("ID_AUTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIVRO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LIVRO" ADD CONSTRAINT "PK_ID_LIVRO" PRIMARY KEY ("ID_LIVRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIVRO_AUTOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LIVRO_AUTOR" ADD CONSTRAINT "PK_LIVRO_AUTOR" PRIMARY KEY ("ID_LIVRO", "ID_AUTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIVRO_AUTOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LIVRO_AUTOR" ADD CONSTRAINT "FK_ID_LIVRO" FOREIGN KEY ("ID_LIVRO")
	  REFERENCES "SYSTEM"."LIVRO" ("ID_LIVRO") ENABLE;
  ALTER TABLE "SYSTEM"."LIVRO_AUTOR" ADD CONSTRAINT "FK_ID_AUTOR" FOREIGN KEY ("ID_AUTOR")
	  REFERENCES "SYSTEM"."AUTOR" ("ID_AUTOR") ENABLE;
